"""add match_confidence to listings

Revision ID: 0c7aa7aec031
Revises: 01b3ba8b463c
Create Date: 2026-08-15 14:59:05.079759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7aa7aec031'
down_revision: Union[str, Sequence[str], None] = '01b3ba8b463c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('match_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'match_confidence')
    # ### end Alembic commands ###
