"""add product_matches table

Revision ID: b1b82de1515c
Revises: 9f58f5cfd17d
Create Date: 2026-08-17 21:00:50.148181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b82de1515c'
down_revision: Union[str, Sequence[str], None] = '9f58f5cfd17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_a_id', sa.Integer(), nullable=False),
    sa.Column('product_b_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_a_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_b_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_a_id', 'product_b_id', name='uq_match_pair')
    )
    op.create_index(op.f('ix_product_matches_product_a_id'), 'product_matches', ['product_a_id'], unique=False)
    op.create_index(op.f('ix_product_matches_product_b_id'), 'product_matches', ['product_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_matches_product_b_id'), table_name='product_matches')
    op.drop_index(op.f('ix_product_matches_product_a_id'), table_name='product_matches')
    op.drop_table('product_matches')
    # ### end Alembic commands ###
